version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/wydddddd/CodeAnalysis"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"